version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    user: postgres
    command: >
      bash -c "
        echo 'Debug: Environment Variables:' &&
        echo 'POSTGRES_DB: '$$POSTGRES_DB &&
        echo 'POSTGRES_USER: '$$POSTGRES_USER &&
        echo 'POSTGRES_PASSWORD: '$$POSTGRES_PASSWORD &&
        if [ -z \"$$POSTGRES_DB\" ] || [ -z \"$$POSTGRES_USER\" ] || [ -z \"$$POSTGRES_PASSWORD\" ]; then
          echo 'Error: Required environment variables are not set'
          echo 'Please set POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD'
          exit 1
        fi &&
        if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Initializing new database...' &&
          initdb -D /var/lib/postgresql/data &&
          echo 'host    all             all             0.0.0.0/0               scram-sha-256' >> /var/lib/postgresql/data/pg_hba.conf &&
          echo 'local   all             all                                     scram-sha-256' >> /var/lib/postgresql/data/pg_hba.conf
        fi &&
        postgres -c 'password_encryption=scram-sha-256' -c 'listen_addresses=*'
      "

  bolt:
    build: .
    ports:
      - '3005:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
