services:
  bolt:
    build: .
    ports:
      - '3005:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Optional debug level
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-info}
      # Add SESSION_SECRET with a default value
      - SESSION_SECRET=${SESSION_SECRET:-bolt-super-secret-session-key-change-in-production-12345}
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      # Persist the SQLite database file
      - ./prisma/dev.db:/app/prisma/dev.db
      # Persist Prisma migrations
      - ./prisma/migrations:/app/prisma/migrations
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
