version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bolt}
      POSTGRES_USER: ${POSTGRES_USER:-bolt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bolt_password_change_in_production}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-bolt} -d ${POSTGRES_DB:-bolt} || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    user: postgres
    command: >
      bash -c "
        echo 'local   all             all                                     scram-sha-256' > /var/lib/postgresql/data/pg_hba.conf &&
        echo 'host    all             all             127.0.0.1/32            scram-sha-256' >> /var/lib/postgresql/data/pg_hba.conf &&
        echo 'host    all             all             ::1/128                 scram-sha-256' >> /var/lib/postgresql/data/pg_hba.conf &&
        echo 'host    all             all             0.0.0.0/0               scram-sha-256' >> /var/lib/postgresql/data/pg_hba.conf &&
        postgres -c 'password_encryption=scram-sha-256' -c 'listen_addresses=*'
      "

  bolt:
    build: .
    ports:
      - '3005:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-bolt}:${POSTGRES_PASSWORD:-bolt_password_change_in_production}@postgres:5432/${POSTGRES_DB:-bolt}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
